modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="xaeroearth"
version="${mod_version}"
displayName="Xaero's World Map: Earth"
description="AUI and 3D map addon for Xaero's World Map"
clientRequired=true

[[dependencies.xaeroearth]]
modId="forge"
mandatory=true
versionRange="${loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.xaeroearth]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.xaeroearth]]
modId="xaeroworldmap"
mandatory=true
versionRange="[1.46.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.xaeroearth]]
modId="apricityui"
mandatory=true
versionRange="[1.2.5.4,)"
ordering="AFTER"
side="CLIENT"
