org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_id=xaeroearth
mod_name=Xaero's World Map: Earth
mod_group_id=io.github.kltyton.xaeroearth
mod_java_package=io.github.kltyton.xaeroearth
mod_entry_class=io.github.kltyton.xaeroearth.client.EarthClient
mod_authors=kltyton
mod_version=0.1.1
mod_license=MIT
mod_description=Native 3D terrain views and an Ore-style interface for Xaero's World Map.
temple_default_target=neoforge-26.2
temple_build_dsl=groovy
temple_idea_project=true
