minecraft_version=26.2
xaero_mc_version=26.2
loader_version=0.19.5
xaero_version=1.46.1
java_version=25
minecraft_version_range=[26.2,26.3)
loader_version_range=[0.19.5,)
loader=fabric
gradle_java_version=25
shared_sources=versions/26.2,common,versions/block-view/min-y,versions/terrain/gpu-26.2,versions/frame-metrics/frame-time,versions/client-screen/26.2,loaders/fabric/common,loaders/fabric/screen/gui,loaders/fabric/lifecycle,loaders/fabric/26-common,loaders/fabric/26.2,versions/26-common,versions/map-height/1.19-26
